version: 1.0.{build}
image: Visual Studio 2013
clone_folder: c:\projects\caffe
build_script:
- ps: >-
    cd C:\projects\caffe\windows

    cp CommonSettings.props.example CommonSettings.props

    nuget restore Caffe.sln

    msbuild Caffe.sln /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:"Configuration=Debug;CpuOnlyBuild=true;UseCuDNN=false"

    msbuild Caffe.sln /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:"Configuration=Release;CpuOnlyBuild=true;UseCuDNN=false;WholeProgramOptimization=false"

    cd ..

    .\Build\Release\test_all.exe --gtest_filter=-*TestTimer*
